---
title: "Nerites"
author: "Olivia Aguiar"
date: "7/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(Biostatistics)
library(readxl)
library(plotrix)
snail <- read_xlsx('LUMSnails_Density_Master_Olivia_08.03.21.xlsx')
```

```{r}
average <- snail %>% 
  group_by(Date) %>% 
  summarise(mean = mean(Nu_density_m2),
            SE = std.error(Nu_density_m2))
```

#graphs
```{r}
snail %>% ggplot() + geom_boxplot(aes(x = Date, y = Nu_density_m2))
#messy

average %>% ggplot(aes(x=Date, y=mean)) + geom_point(aes(x=Date, y=mean)) + geom_errorbar(aes(ymin = mean-SE, ymax = mean+SE)) + xlab('Date') + ylab('Nerite Density') + theme(axis.text.x = element_text(size = 7, angle = 45), axis.ticks = element_blank()) + scale_x_discrete(limits = c('01/2017', '02/2017', '03/2017', '04/2017', '05/2017', '06/2017', '07/2017', '08/2017', '09/2017', '10/2017', '11/2017', '12/2017', '01/2018', '02/2018', '03/2018', '04/2018', '05/2018', '06/2018', '07/2018', '08/2018', '09/2018', '10/2018', '11/2018', '12/2018', '01/2019', '02/2019', '03/2019', '04/2019', '05/2019', '06/2019', '07/2019', '08/2019', '09/2019', '10/2019', '11/2019', '12/2019', '01/2020', '02/2020', '03/2020', '04/2020', '05/2020', '06/2020', '07/2020', '08/2020', '09/2020', '10/2020', '11/2020', '12/2020', '01/2021', '02/2021', '03/2021', '04/2021', '05/2021', '06/2021'))
```

#does nucella density vary by site?
```{r}
nu.aov <- aov(Nu_density_m2 ~ site, snail)
summary(nu.aov)
TukeyHSD(nu.aov)
#LUM2 significantly greater than other sites- very large outlier though

snail %>% ggplot() + geom_boxplot(aes(x=site, y=Nu_density_m2)) + xlab('Site') + ylab('Nerite Density')
```

#making data frame for each site
```{r}
snail$season <- snail$month_name
snail$season <- gsub('Dec', 'Winter', snail$season)
snail$season <- gsub('Jan', 'Winter', snail$season)
snail$season <- gsub('Feb', 'Winter', snail$season)
snail$season <- gsub('Mar', 'Spring', snail$season)
snail$season <- gsub('Apr', 'Spring', snail$season)
snail$season <- gsub('May', 'Spring', snail$season)
snail$season <- gsub('Jun', 'Summer', snail$season)
snail$season <- gsub('Jul', 'Summer', snail$season)
snail$season <- gsub('Aug', 'Summer', snail$season)
snail$season <- gsub('Sep', 'Fall', snail$season)
snail$season <- gsub('Oct', 'Fall', snail$season)
snail$season <- gsub('Nov', 'Fall', snail$season)
snail1 <- snail %>% subset(site == 'LUM1')
snail2 <- snail %>% subset(site == 'LUM2')
snail3 <- snail %>% subset(site == 'LUM3')

average1 <- snail1 %>% 
  group_by(Date) %>% 
  summarise(mean = mean(Nu_density_m2),
            SE = std.error(Nu_density_m2))

average2 <- snail2 %>% 
  group_by(Date) %>% 
  summarise(mean = mean(Nu_density_m2),
            SE = std.error(Nu_density_m2))

average3 <- snail3 %>% 
  group_by(Date) %>% 
  summarise(mean = mean(Nu_density_m2),
            SE = std.error(Nu_density_m2))
```

#graphs for each site
```{r}
#LUM1
average1 %>% ggplot(aes(x=Date, y=mean)) + geom_point(aes(x=Date, y=mean)) + geom_errorbar(aes(ymin = mean-SE, ymax = mean+SE)) + xlab('Date') + ylab('Nerite Density') + theme(axis.text.x = element_text(size = 7, angle = 45), axis.ticks = element_blank()) + ggtitle('LUM1') + scale_x_discrete(limits = c('01/2017', '02/2017', '03/2017', '04/2017', '05/2017', '06/2017', '07/2017', '08/2017', '09/2017', '10/2017', '11/2017', '12/2017', '01/2018', '02/2018', '03/2018', '04/2018', '05/2018', '06/2018', '07/2018', '08/2018', '09/2018', '10/2018', '11/2018', '12/2018', '01/2019', '02/2019', '03/2019', '04/2019', '05/2019', '06/2019', '07/2019', '08/2019', '09/2019', '10/2019', '11/2019', '12/2019', '01/2020', '02/2020', '03/2020', '04/2020', '05/2020', '06/2020', '07/2020', '08/2020', '09/2020', '10/2020', '11/2020', '12/2020', '01/2021', '02/2021', '03/2021', '04/2021', '05/2021', '06/2021'))

#LUM2
average2 %>% ggplot(aes(x=Date, y=mean)) + geom_point(aes(x=Date, y=mean)) + geom_errorbar(aes(ymin = mean-SE, ymax = mean+SE)) + xlab('Date') + ylab('Nerite Density') + theme(axis.text.x = element_text(size = 7, angle = 45), axis.ticks = element_blank()) + ggtitle('LUM2') + scale_x_discrete(limits = c('01/2017', '02/2017', '03/2017', '04/2017', '05/2017', '06/2017', '07/2017', '08/2017', '09/2017', '10/2017', '11/2017', '12/2017', '01/2018', '02/2018', '03/2018', '04/2018', '05/2018', '06/2018', '07/2018', '08/2018', '09/2018', '10/2018', '11/2018', '12/2018', '01/2019', '02/2019', '03/2019', '04/2019', '05/2019', '06/2019', '07/2019', '08/2019', '09/2019', '10/2019', '11/2019', '12/2019', '01/2020', '02/2020', '03/2020', '04/2020', '05/2020', '06/2020', '07/2020', '08/2020', '09/2020', '10/2020', '11/2020', '12/2020', '01/2021', '02/2021', '03/2021', '04/2021', '05/2021', '06/2021'))

#LUM3
average3 %>% ggplot(aes(x=Date, y=mean)) + geom_point(aes(x=Date, y=mean)) + geom_errorbar(aes(ymin = mean-SE, ymax = mean+SE)) + xlab('Date') + ylab('Nerite Density') + theme(axis.text.x = element_text(size = 7, angle = 45), axis.ticks = element_blank()) + ggtitle('LUM3') + scale_x_discrete(limits = c('01/2017', '02/2017', '03/2017', '04/2017', '05/2017', '06/2017', '07/2017', '08/2017', '09/2017', '10/2017', '11/2017', '12/2017', '01/2018', '02/2018', '03/2018', '04/2018', '05/2018', '06/2018', '07/2018', '08/2018', '09/2018', '10/2018', '11/2018', '12/2018', '01/2019', '02/2019', '03/2019', '04/2019', '05/2019', '06/2019', '07/2019', '08/2019', '09/2019', '10/2019', '11/2019', '12/2019', '01/2020', '02/2020', '03/2020', '04/2020', '05/2020', '06/2020', '07/2020', '08/2020', '09/2020', '10/2020', '11/2020', '12/2020', '01/2021', '02/2021', '03/2021', '04/2021', '05/2021', '06/2021'))
```

#seasonal plots
```{r}
snail1 %>% ggplot() + geom_boxplot(aes(x = season, y = Nu_density_m2)) + xlab('Season') + ylab('Nerite Density') + ggtitle('LUM1')

snail1.aov <- aov(Nu_density_m2 ~ season, snail1)
summary(snail1.aov)

snail2 %>% ggplot() + geom_boxplot(aes(x = season, y = Nu_density_m2)) + xlab('Season') + ylab('Nerite Density') + ggtitle('LUM2')

snail2.aov <- aov(Nu_density_m2 ~ season, snail2)
summary(snail2.aov)
#almost significant

snail3 %>% ggplot() + geom_boxplot(aes(x = season, y = Nu_density_m2)) + xlab('Season') + ylab('Nerite Density') + ggtitle('LUM3')

snail3.aov <- aov(Nu_density_m2 ~ season, snail3)
summary(snail3.aov)
```

#yearly plot
```{r}
snail1$year <- as.character(snail1$year)
snail1 %>% ggplot() + geom_boxplot(aes(x = year, y = Nu_density_m2)) + xlab('Year') + ylab('Nerite density (m2)') + ggtitle('LUM1')

snail2$year <- as.character(snail2$year)
snail2 %>% ggplot() + geom_boxplot(aes(x = year, y = Nu_density_m2)) + xlab('Year') + ylab('Nerite density (m2)') + ggtitle('LUM2')

snail3$year <- as.character(snail3$year)
snail2 %>% ggplot() + geom_boxplot(aes(x = year, y = Nu_density_m2)) + xlab('Year') + ylab('Nerite density (m2)') + ggtitle('LUM3')
```

#monthly plots
#LUM1
```{r}
month_order <- c('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec')
snail1.17 <- snail1 %>% subset(year == '2017') %>%
  group_by(month_name) %>%
  summarise(mean = mean(Nu_density_m2),
            SE = std.error(Nu_density_m2))
snail1.17 %>% ggplot(aes(x=factor(month_name, levels = month_order), y=mean)) + geom_point(aes(x=factor(month_name, levels = month_order), y=mean)) + geom_errorbar(aes(ymin = mean-SE, ymax = mean+SE)) + xlab('Month') + ylab('Nerite Density') + ggtitle('LUM1 Nerite Density in 2017')


snail1.18 <- snail1 %>% subset(year == '2018') %>%
  group_by(month_name) %>%
  summarise(mean = mean(Nu_density_m2),
            SE = std.error(Nu_density_m2))
snail1.18 %>% ggplot(aes(x=factor(month_name, levels = month_order), y=mean)) + geom_point(aes(x=factor(month_name, levels = month_order), y=mean)) + geom_errorbar(aes(ymin = mean-SE, ymax = mean+SE)) + xlab('Month') + ylab('Nerite Density') + ggtitle('LUM1 Nerite Density in 2018')


snail1.19 <- snail1 %>% subset(year == '2019') %>%
  group_by(month_name) %>%
  summarise(mean = mean(Nu_density_m2), 
            SE = std.error(Nu_density_m2))
snail1.19 %>% ggplot(aes(x=factor(month_name, levels = month_order), y=mean)) + geom_point(aes(x=factor(month_name, levels = month_order), y=mean)) + geom_errorbar(aes(ymin = mean-SE, ymax = mean+SE)) + xlab('Month') + ylab('Nerite Density') + ggtitle('LUM1 Nerite Density in 2019')


snail1.20 <- snail1 %>% subset(year == '2020') %>%
  group_by(month_name) %>%
  summarise(mean = mean(Nu_density_m2),
            SE = std.error(Nu_density_m2))
snail1.20 %>% ggplot(aes(x=factor(month_name, levels = month_order), y=mean)) + geom_point(aes(x=factor(month_name, levels = month_order), y=mean)) + geom_errorbar(aes(ymin = mean-SE, ymax = mean+SE)) + xlab('Month') + ylab('Nerite Density') + ggtitle('LUM1 Nerite Density in 2020')

month_order2 <- c('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun')
snail1.21 <- snail1 %>% subset(year == '2021') %>%
  group_by(month_name) %>%
  summarise(mean = mean(Nu_density_m2),
            SE = std.error(Nu_density_m2))
snail1.21 %>% ggplot(aes(x=factor(month_name, levels = month_order2), y=mean)) + geom_point(aes(x=factor(month_name, levels = month_order2), y=mean)) + geom_errorbar(aes(ymin = mean-SE, ymax = mean+SE)) + xlab('Month') + ylab('Nerite Density') + ggtitle('LUM1 Nerite Density in 2021')
```

#LUM2
```{r}
snail2.17 <- snail2 %>% subset(year == '2017') %>%
  group_by(month_name) %>%
  summarise(mean = mean(Nu_density_m2),
            SE = std.error(Nu_density_m2))
snail2.17 %>% ggplot(aes(x=factor(month_name, levels = month_order), y=mean)) + geom_point(aes(x=factor(month_name, levels = month_order), y=mean)) + geom_errorbar(aes(ymin = mean-SE, ymax = mean+SE)) + xlab('Month') + ylab('Nerite Density') + ggtitle('LUM2 Nerite Density in 2017')


snail2.18 <- snail2 %>% subset(year == '2018') %>%
  group_by(month_name) %>%
  summarise(mean = mean(Nu_density_m2),
            SE = std.error(Nu_density_m2))
snail2.18 %>% ggplot(aes(x=factor(month_name, levels = month_order), y=mean)) + geom_point(aes(x=factor(month_name, levels = month_order), y=mean)) + geom_errorbar(aes(ymin = mean-SE, ymax = mean+SE)) + xlab('Month') + ylab('Nerite Density') + ggtitle('LUM2 Nerite Density in 2018')


snail2.19 <- snail2 %>% subset(year == '2019') %>%
  group_by(month_name) %>%
  summarise(mean = mean(Nu_density_m2), 
            SE = std.error(Nu_density_m2))
snail2.19 %>% ggplot(aes(x=factor(month_name, levels = month_order), y=mean)) + geom_point(aes(x=factor(month_name, levels = month_order), y=mean)) + geom_errorbar(aes(ymin = mean-SE, ymax = mean+SE)) + xlab('Month') + ylab('Nerite Density') + ggtitle('LUM2 Nerite Density in 2019')


snail2.20 <- snail2 %>% subset(year == '2020') %>%
  group_by(month_name) %>%
  summarise(mean = mean(Nu_density_m2),
            SE = std.error(Nu_density_m2))
snail2.20 %>% ggplot(aes(x=factor(month_name, levels = month_order), y=mean)) + geom_point(aes(x=factor(month_name, levels = month_order), y=mean)) + geom_errorbar(aes(ymin = mean-SE, ymax = mean+SE)) + xlab('Month') + ylab('Nerite Density') + ggtitle('LUM2 Nerite Density in 2020')


snail2.21 <- snail2 %>% subset(year == '2021') %>%
  group_by(month_name) %>%
  summarise(mean = mean(Nu_density_m2),
            SE = std.error(Nu_density_m2))
snail2.21 %>% ggplot(aes(x=factor(month_name, levels = month_order2), y=mean)) + geom_point(aes(x=factor(month_name, levels = month_order2), y=mean)) + geom_errorbar(aes(ymin = mean-SE, ymax = mean+SE)) + xlab('Month') + ylab('Nerite Density') + ggtitle('LUM2 Nerite Density in 2021')
```

#LUM3
```{r}
snail3.17 <- snail3 %>% subset(year == '2017') %>%
  group_by(month_name) %>%
  summarise(mean = mean(Nu_density_m2),
            SE = std.error(Nu_density_m2))
snail3.17 %>% ggplot(aes(x=factor(month_name, levels = month_order), y=mean)) + geom_point(aes(x=factor(month_name, levels = month_order), y=mean)) + geom_errorbar(aes(ymin = mean-SE, ymax = mean+SE)) + xlab('Month') + ylab('Nerite Density') + ggtitle('LUM3 Nerite Density in 2017')


snail3.18 <- snail3 %>% subset(year == '2018') %>%
  group_by(month_name) %>%
  summarise(mean = mean(Nu_density_m2),
            SE = std.error(Nu_density_m2))
snail3.18 %>% ggplot(aes(x=factor(month_name, levels = month_order), y=mean)) + geom_point(aes(x=factor(month_name, levels = month_order), y=mean)) + geom_errorbar(aes(ymin = mean-SE, ymax = mean+SE)) + xlab('Month') + ylab('Nerite Density') + ggtitle('LUM3 Nerite Density in 2018')


snail3.19 <- snail3 %>% subset(year == '2019') %>%
  group_by(month_name) %>%
  summarise(mean = mean(Nu_density_m2), 
            SE = std.error(Nu_density_m2))
snail3.19 %>% ggplot(aes(x=factor(month_name, levels = month_order), y=mean)) + geom_point(aes(x=factor(month_name, levels = month_order), y=mean)) + geom_errorbar(aes(ymin = mean-SE, ymax = mean+SE)) + xlab('Month') + ylab('Nerite Density') + ggtitle('LUM3 Nerite Density in 2019')


snail3.20 <- snail3 %>% subset(year == '2020') %>%
  group_by(month_name) %>%
  summarise(mean = mean(Nu_density_m2),
            SE = std.error(Nu_density_m2))
snail3.20 %>% ggplot(aes(x=factor(month_name, levels = month_order), y=mean)) + geom_point(aes(x=factor(month_name, levels = month_order), y=mean)) + geom_errorbar(aes(ymin = mean-SE, ymax = mean+SE)) + xlab('Month') + ylab('Nerite Density') + ggtitle('LUM3 Nerite Density in 2020')


snail3.21 <- snail3 %>% subset(year == '2021') %>%
  group_by(month_name) %>%
  summarise(mean = mean(Nu_density_m2),
            SE = std.error(Nu_density_m2))
snail3.21 %>% ggplot(aes(x=factor(month_name, levels = month_order2), y=mean)) + geom_point(aes(x=factor(month_name, levels = month_order2), y=mean)) + geom_errorbar(aes(ymin = mean-SE, ymax = mean+SE)) + xlab('Month') + ylab('Nerite Density') + ggtitle('LUM3 Nerite Density in 2021')
```

