---
title: "Stem Density"
author: "Olivia Aguiar"
date: "7/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(tidyverse)
library(Biostatistics)
library(plotrix)
library(lubridate)
```

#bring in data
```{r}
plants <- read_xlsx('LUMCON Plants_StemDensity_Master_Olivia_08.03.21.xlsx')
#plants$new_date <- as.Date(plants$date, "%mm/%YYYY", tryFormats = c("%m/%Y"), optional = TRUE)
#this isn't working!

#moving on, I'm going to separate the density column into two separate columns to make things easier


#cast and melt for separating things out?
plants1 <- plants %>% filter(site == 'LUM1')
plants2 <- plants %>% filter(site == 'LUM2')
plants3 <- plants %>% filter(site == 'LUM3')
```

#idk what im doing here but ¯\_(ツ)_/¯
#dead plants LUM1 by month
```{r}
plants1.dead <- plants1 %>% filter(status == 'DEAD')

dead1 <- plants1.dead %>% 
  group_by(date) %>% 
  summarise(mean = mean(density),
            std = sd(density))

dead1 %>% ggplot(aes(x=date, y=mean)) + geom_point(aes(x=date, y=mean)) + geom_errorbar(aes(ymin = mean-std, ymax = mean+std)) + xlab('Date') + ylab('Stem Density') + ggtitle('LUM1 Dead Stem Density') + theme(axis.text.x = element_text(size = 7, angle = 45), axis.ticks = element_blank()) + scale_x_discrete(limits = c('01/2017', '02/2017', '03/2017', '04/2017', '05/2017', '06/2017', '07/2017', '08/2017', '09/2017', '10/2017', '11/2017', '12/2017', '01/2018', '02/2018', '03/2018', '04/2018', '05/2018', '06/2018', '07/2018', '08/2018', '09/2018', '10/2018', '11/2018', '12/2018', '01/2019', '02/2019', '03/2019', '04/2019', '05/2019', '06/2019', '07/2019', '08/2019', '09/2019', '10/2019', '11/2019', '12/2019', '01/2020', '02/2020', '03/2020', '04/2020', '05/2020', '06/2020', '07/2020', '08/2020', '09/2020', '10/2020', '11/2020', '12/2020', '01/2021', '02/2021', '03/2021', '04/2021', '05/2021', '06/2021'))
```

#dead plants LUM2 by month
```{r}
plants2.dead <- plants2 %>% filter(status == 'DEAD')

dead2 <- plants2.dead %>% 
  group_by(date) %>% 
  summarise(mean = mean(density),
            std = sd(density))

dead2 %>% ggplot(aes(x=date, y=mean)) + geom_point(aes(x=date, y=mean)) + geom_errorbar(aes(ymin = mean-std, ymax = mean+std)) + xlab('Date') + ylab('Stem Density') + ggtitle('LUM2 Dead Stem Density') + theme(axis.text.x = element_text(size = 7, angle = 45), axis.ticks = element_blank()) + scale_x_discrete(limits = c('01/2017', '02/2017', '03/2017', '04/2017', '05/2017', '06/2017', '07/2017', '08/2017', '09/2017', '10/2017', '11/2017', '12/2017', '01/2018', '02/2018', '03/2018', '04/2018', '05/2018', '06/2018', '07/2018', '08/2018', '09/2018', '10/2018', '11/2018', '12/2018', '01/2019', '02/2019', '03/2019', '04/2019', '05/2019', '06/2019', '07/2019', '08/2019', '09/2019', '10/2019', '11/2019', '12/2019', '01/2020', '02/2020', '03/2020', '04/2020', '05/2020', '06/2020', '07/2020', '08/2020', '09/2020', '10/2020', '11/2020', '12/2020', '01/2021', '02/2021', '03/2021', '04/2021', '05/2021', '06/2021'))
```

#dead plants LUM3 by month
```{r}
plants3.dead <- plants3 %>% filter(status == 'DEAD')

dead3 <- plants3.dead %>% 
  group_by(date) %>% 
  summarise(mean = mean(density),
            std = sd(density))

dead3 %>% ggplot(aes(x=date, y=mean)) + geom_point(aes(x=date, y=mean)) + geom_errorbar(aes(ymin = mean-std, ymax = mean+std)) + xlab('Date') + ylab('Stem Density') + ggtitle('LUM3 Dead Stem Density') + theme(axis.text.x = element_text(size = 7, angle = 45), axis.ticks = element_blank()) + scale_x_discrete(limits = c('01/2017', '02/2017', '03/2017', '04/2017', '05/2017', '06/2017', '07/2017', '08/2017', '09/2017', '10/2017', '11/2017', '12/2017', '01/2018', '02/2018', '03/2018', '04/2018', '05/2018', '06/2018', '07/2018', '08/2018', '09/2018', '10/2018', '11/2018', '12/2018', '01/2019', '02/2019', '03/2019', '04/2019', '05/2019', '06/2019', '07/2019', '08/2019', '09/2019', '10/2019', '11/2019', '12/2019', '01/2020', '02/2020', '03/2020', '04/2020', '05/2020', '06/2020', '07/2020', '08/2020', '09/2020', '10/2020', '11/2020', '12/2020', '01/2021', '02/2021', '03/2021', '04/2021', '05/2021', '06/2021'))
```

#live plants LUM1 by month
```{r}
plants1.live <- plants1 %>% filter(status == 'LIVE')

live1 <- plants1.live %>% 
  group_by(date) %>% 
  summarise(mean = mean(density),
            std = sd(density))

live1 %>% ggplot(aes(x=date, y=mean)) + geom_point(aes(x=date, y=mean)) + geom_errorbar(aes(ymin = mean-std, ymax = mean+std)) + xlab('Date') + ylab('Stem Density') + ggtitle('LUM1 Live Stem Density') + theme(axis.text.x = element_text(size = 7, angle = 45), axis.ticks = element_blank()) + scale_x_discrete(limits = c('01/2017', '02/2017', '03/2017', '04/2017', '05/2017', '06/2017', '07/2017', '08/2017', '09/2017', '10/2017', '11/2017', '12/2017', '01/2018', '02/2018', '03/2018', '04/2018', '05/2018', '06/2018', '07/2018', '08/2018', '09/2018', '10/2018', '11/2018', '12/2018', '01/2019', '02/2019', '03/2019', '04/2019', '05/2019', '06/2019', '07/2019', '08/2019', '09/2019', '10/2019', '11/2019', '12/2019', '01/2020', '02/2020', '03/2020', '04/2020', '05/2020', '06/2020', '07/2020', '08/2020', '09/2020', '10/2020', '11/2020', '12/2020', '01/2021', '02/2021', '03/2021', '04/2021', '05/2021', '06/2021'))
```

#live plants LUM2 by month
```{r}
plants2.live <- plants2 %>% filter(status == 'LIVE')

live2 <- plants2.live %>% 
  group_by(date) %>% 
  summarise(mean = mean(density),
            std = sd(density))

live2 %>% ggplot(aes(x=date, y=mean)) + geom_point(aes(x=date, y=mean)) + geom_errorbar(aes(ymin = mean-std, ymax = mean+std)) + xlab('Date') + ylab('Stem Density') + ggtitle('LUM2 Live Stem Density') + theme(axis.text.x = element_text(size = 7, angle = 45), axis.ticks = element_blank()) + scale_x_discrete(limits = c('01/2017', '02/2017', '03/2017', '04/2017', '05/2017', '06/2017', '07/2017', '08/2017', '09/2017', '10/2017', '11/2017', '12/2017', '01/2018', '02/2018', '03/2018', '04/2018', '05/2018', '06/2018', '07/2018', '08/2018', '09/2018', '10/2018', '11/2018', '12/2018', '01/2019', '02/2019', '03/2019', '04/2019', '05/2019', '06/2019', '07/2019', '08/2019', '09/2019', '10/2019', '11/2019', '12/2019', '01/2020', '02/2020', '03/2020', '04/2020', '05/2020', '06/2020', '07/2020', '08/2020', '09/2020', '10/2020', '11/2020', '12/2020', '01/2021', '02/2021', '03/2021', '04/2021', '05/2021', '06/2021'))
```

#live plants LUM3 by month
```{r}
plants3.live <- plants3 %>% filter(status == 'LIVE')

live3 <- plants3.live %>% 
  group_by(date) %>% 
  summarise(mean = mean(density),
            std = sd(density))

live3 %>% ggplot(aes(x=date, y=mean)) + geom_point(aes(x=date, y=mean)) + geom_errorbar(aes(ymin = mean-std, ymax = mean+std)) + xlab('Date') + ylab('Stem Density') + ggtitle('LUM3 Live Stem Density') + theme(axis.text.x = element_text(size = 7, angle = 45), axis.ticks = element_blank()) + scale_x_discrete(limits = c('01/2017', '02/2017', '03/2017', '04/2017', '05/2017', '06/2017', '07/2017', '08/2017', '09/2017', '10/2017', '11/2017', '12/2017', '01/2018', '02/2018', '03/2018', '04/2018', '05/2018', '06/2018', '07/2018', '08/2018', '09/2018', '10/2018', '11/2018', '12/2018', '01/2019', '02/2019', '03/2019', '04/2019', '05/2019', '06/2019', '07/2019', '08/2019', '09/2019', '10/2019', '11/2019', '12/2019', '01/2020', '02/2020', '03/2020', '04/2020', '05/2020', '06/2020', '07/2020', '08/2020', '09/2020', '10/2020', '11/2020', '12/2020', '01/2021', '02/2021', '03/2021', '04/2021', '05/2021', '06/2021'))
```

#tring to combine dead and live df now
#LUM1 monthly
```{r}
#renaming columns so it doesn't get confusing
colnames(dead1)[colnames(dead1) == 'mean'] <- 'dead_mean'
colnames(dead1)[colnames(dead1) == 'std'] <- 'dead_std'
colnames(live1)[colnames(live1) == 'mean'] <- 'live_mean'
colnames(live1)[colnames(live1) == 'std'] <- 'live_std'

stems1 <- live1
stems1$dead_mean <- dead1$dead_mean
stems1$dead_std <- dead1$dead_std

ggplot(plants1, aes(x = date, y = density, fill = status)) + geom_col(position = 'fill') + theme(axis.text.x = element_text(size = 7, angle = 45), axis.ticks = element_blank()) + scale_x_discrete(limits = c('01/2017', '02/2017', '03/2017', '04/2017', '05/2017', '06/2017', '07/2017', '08/2017', '09/2017', '10/2017', '11/2017', '12/2017', '01/2018', '02/2018', '03/2018', '04/2018', '05/2018', '06/2018', '07/2018', '08/2018', '09/2018', '10/2018', '11/2018', '12/2018', '01/2019', '02/2019', '03/2019', '04/2019', '05/2019', '06/2019', '07/2019', '08/2019', '09/2019', '10/2019', '11/2019', '12/2019', '01/2020', '02/2020', '03/2020', '04/2020', '05/2020', '06/2020', '07/2020', '08/2020', '09/2020', '10/2020', '11/2020', '12/2020', '01/2021', '02/2021', '03/2021', '04/2021')) + xlab('Date') + ylab('Propotion of Dead to Live Stems') + ggtitle('LUM1')
```

#LUM2 monthly
```{r}
colnames(dead2)[colnames(dead2) == 'mean'] <- 'dead_mean'
colnames(dead2)[colnames(dead2) == 'std'] <- 'dead_std'
colnames(live2)[colnames(live2) == 'mean'] <- 'live_mean'
colnames(live2)[colnames(live2) == 'std'] <- 'live_std'

stems2 <- live2
stems2$dead_mean <- dead2$dead_mean
stems2$dead_std <- dead2$dead_std

ggplot(plants2, aes(x = date, y = density, fill = status)) + geom_col(position = 'fill') + theme(axis.text.x = element_text(size = 7, angle = 45), axis.ticks = element_blank()) + scale_x_discrete(limits = c('01/2017', '02/2017', '03/2017', '04/2017', '05/2017', '06/2017', '07/2017', '08/2017', '09/2017', '10/2017', '11/2017', '12/2017', '01/2018', '02/2018', '03/2018', '04/2018', '05/2018', '06/2018', '07/2018', '08/2018', '09/2018', '10/2018', '11/2018', '12/2018', '01/2019', '02/2019', '03/2019', '04/2019', '05/2019', '06/2019', '07/2019', '08/2019', '09/2019', '10/2019', '11/2019', '12/2019', '01/2020', '02/2020', '03/2020', '04/2020', '05/2020', '06/2020', '07/2020', '08/2020', '09/2020', '10/2020', '11/2020', '12/2020', '01/2021', '02/2021', '03/2021', '04/2021')) + xlab('Date') + ylab('Propotion of Dead to Live Stems') + ggtitle('LUM2')
```

#LUM3 monthly
```{r}
colnames(dead3)[colnames(dead3) == 'mean'] <- 'dead_mean'
colnames(dead3)[colnames(dead3) == 'std'] <- 'dead_std'
colnames(live3)[colnames(live3) == 'mean'] <- 'live_mean'
colnames(live3)[colnames(live3) == 'std'] <- 'live_std'

stems3 <- live3
stems3$dead_mean <- dead3$dead_mean
stems3$dead_std <- dead3$dead_std

ggplot(plants3, aes(x = date, y = density, fill = status)) + geom_col(position = 'fill') + theme(axis.text.x = element_text(size = 7, angle = 45), axis.ticks = element_blank()) + scale_x_discrete(limits = c('01/2017', '02/2017', '03/2017', '04/2017', '05/2017', '06/2017', '07/2017', '08/2017', '09/2017', '10/2017', '11/2017', '12/2017', '01/2018', '02/2018', '03/2018', '04/2018', '05/2018', '06/2018', '07/2018', '08/2018', '09/2018', '10/2018', '11/2018', '12/2018', '01/2019', '02/2019', '03/2019', '04/2019', '05/2019', '06/2019', '07/2019', '08/2019', '09/2019', '10/2019', '11/2019', '12/2019', '01/2020', '02/2020', '03/2020', '04/2020', '05/2020', '06/2020', '07/2020', '08/2020', '09/2020', '10/2020', '11/2020', '12/2020', '01/2021', '02/2021', '03/2021', '04/2021')) + xlab('Date') + ylab('Proportion of Dead to Live Stems') + ggtitle('LUM3')
```

#LUM1 yearly
```{r}
ggplot(plants1, aes(x = year, y = density, fill = status)) + geom_col(position = 'fill') + xlab('Date') + ylab('Propotion of Dead to Live Stems') + ggtitle('LUM1')
```

#LUM2 yearly
```{r}
ggplot(plants2, aes(x = year, y = density, fill = status)) + geom_col(position = 'fill') + xlab('Date') + ylab('Propotion of Dead to Live Stems') + ggtitle('LUM2')
```

#LUM3 yearly
```{r}
ggplot(plants3, aes(x = year, y = density, fill = status)) + geom_col(position = 'fill') + xlab('Date') + ylab('Propotion of Dead to Live Stems') + ggtitle('LUM3')
```

#all live stem density
```{r}
plants.live <- plants %>% subset(status == 'LIVE') %>% subset(year != 2016) %>% group_by(date) %>%
  summarise(
    mean = mean(density),
    SE = std.error(density)
  )

plants.live$date <- my(plants.live$date,quiet=FALSE, tz=NULL, locale=Sys.getlocale("LC_TIME"))

plants.live %>% ggplot(aes(x = date, y = mean)) + geom_point(aes(c = date, y = mean)) + geom_errorbar(aes(ymin = mean-SE, ymax = mean+SE)) + xlab('Date') + ylab('Stem Density') + ggtitle('Live Stem Density') + scale_y_continuous(breaks = c(0, 300, 500, 700), labels = c(0, 300, 500, 700)) + theme_bw()
```

