---
title: "Water_Salinity"
author: "Olivia Aguiar"
date: "7/31/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(tidyverse)
library(Biostatistics)
library(plotrix)
library(lubridate)
```

```{r}
big <- read_xlsx('MC_Salinity_WaterTemp.xlsx', sheet = 'MC_Salinity') %>% na.omit()
new <- read_xlsx('MC_WaterDepth_Salinity_WaterTemp.xlsx', sheet = 'Salinity')
combined <- rbind(big, new)
combined$`Month/Year` <- format(as.Date(combined$`Date/Time`), "%m/%Y")
combined$`Month/Date` <- format(as.Date(combined$`Date/Time`), '%m/%d')
combined$Year <- format(as.Date(combined$`Date/Time`), '%Y')
combined$Month <- format(as.Date(combined$`Date/Time`), '%m')
sal <- combined %>% subset(Year == '2017' | Year == '2018' | Year == '2019' | Year == '2020' | Year == '2021')
```

#yearly boxplot
```{r}
sal %>% ggplot() + geom_boxplot(aes(x = Year, y = Sal)) + ylab('Water Salinity')

year.aov <- aov(Sal ~ Year, sal)
summary(year.aov)
TukeyHSD(year.aov)
#all of the years are different?
```

#monthly boxplot
```{r}
#2017
sal %>% subset(Year == '2017') %>% ggplot() + geom_boxplot(aes(x = Month, y = Sal)) + ylab('Salinity') + ggtitle('Water Salinity in 2017')

#2018
sal %>% subset(Year == '2018') %>% ggplot() + geom_boxplot(aes(x = Month, y = Sal)) + ylab('Salinity') + ggtitle('Water Salinity in 2018')

#2019
sal %>% subset(Year == '2019') %>% ggplot() + geom_boxplot(aes(x = Month, y = Sal)) + ylab('Salinity') + ggtitle('Water Salinity in 2019')

#2020
sal %>% subset(Year == '2020') %>% ggplot() + geom_boxplot(aes(x = Month, y = Sal)) + ylab('Salinity') + ggtitle('Water Salinity in 2020')

#2021
sal %>% subset(Year == '2021') %>% ggplot() + geom_boxplot(aes(x = Month, y = Sal)) + ylab('Salinity') + ggtitle('Water Salinity in 2021')

```

#seasonal boxplot
```{r}
sal$Season <- sal$`Month/Year`
sal$Season <- gsub('01/2017', 'Winter', sal$Season) 
sal$Season <- gsub('02/2017', 'Winter', sal$Season) 
sal$Season <- gsub('03/2017', 'Spring', sal$Season) 
sal$Season <- gsub('04/2017', 'Spring', sal$Season) 
sal$Season <- gsub('05/2017', 'Spring', sal$Season) 
sal$Season <- gsub('06/2017', 'Summer', sal$Season) 
sal$Season <- gsub('07/2017', 'Summer', sal$Season) 
sal$Season <- gsub('08/2017', 'Summer', sal$Season) 
sal$Season <- gsub('09/2017', 'Fall', sal$Season) 
sal$Season <- gsub('10/2017', 'Fall', sal$Season) 
sal$Season <- gsub('11/2017', 'Fall', sal$Season) 
sal$Season <- gsub('12/2017', 'Winter', sal$Season)

sal$Season <- gsub('01/2018', 'Winter', sal$Season) 
sal$Season <- gsub('02/2018', 'Winter', sal$Season) 
sal$Season <- gsub('03/2018', 'Spring', sal$Season) 
sal$Season <- gsub('04/2018', 'Spring', sal$Season) 
sal$Season <- gsub('05/2018', 'Spring', sal$Season) 
sal$Season <- gsub('06/2018', 'Summer', sal$Season) 
sal$Season <- gsub('07/2018', 'Summer', sal$Season) 
sal$Season <- gsub('08/2018', 'Summer', sal$Season) 
sal$Season <- gsub('09/2018', 'Fall', sal$Season) 
sal$Season <- gsub('10/2018', 'Fall', sal$Season) 
sal$Season <- gsub('11/2018', 'Fall', sal$Season) 
sal$Season <- gsub('12/2018', 'Winter', sal$Season) 

sal$Season <- gsub('01/2019', 'Winter', sal$Season) 
sal$Season <- gsub('02/2019', 'Winter', sal$Season) 
sal$Season <- gsub('03/2019', 'Spring', sal$Season) 
sal$Season <- gsub('04/2019', 'Spring', sal$Season) 
sal$Season <- gsub('05/2019', 'Spring', sal$Season) 
sal$Season <- gsub('06/2019', 'Summer', sal$Season) 
sal$Season <- gsub('07/2019', 'Summer', sal$Season) 
sal$Season <- gsub('08/2019', 'Summer', sal$Season) 
sal$Season <- gsub('09/2019', 'Fall', sal$Season) 
sal$Season <- gsub('10/2019', 'Fall', sal$Season) 
sal$Season <- gsub('11/2019', 'Fall', sal$Season) 
sal$Season <- gsub('12/2019', 'Winter', sal$Season) 

sal$Season <- gsub('01/2020', 'Winter', sal$Season) 
sal$Season <- gsub('02/2020', 'Winter', sal$Season) 
sal$Season <- gsub('03/2020', 'Spring', sal$Season) 
sal$Season <- gsub('04/2020', 'Spring', sal$Season) 
sal$Season <- gsub('05/2020', 'Spring', sal$Season) 
sal$Season <- gsub('06/2020', 'Summer', sal$Season) 
sal$Season <- gsub('07/2020', 'Summer', sal$Season) 
sal$Season <- gsub('08/2020', 'Summer', sal$Season) 
sal$Season <- gsub('09/2020', 'Fall', sal$Season) 
sal$Season <- gsub('10/2020', 'Fall', sal$Season) 
sal$Season <- gsub('11/2020', 'Fall', sal$Season) 
sal$Season <- gsub('12/2020', 'Winter', sal$Season)

sal %>% ggplot() + geom_boxplot(aes(x = Season, y = Sal)) + ylab('Water Salinity')
```

#point plot for entire study period
```{r}
average <- sal %>% 
  group_by(`Month/Year`) %>% 
  summarise(mean = mean(Sal, na.rm = TRUE),
            SE = std.error(Sal))
average %>% ggplot(aes(x=`Month/Year`, y=mean)) + geom_point(aes(x=`Month/Year`, y=mean)) + geom_errorbar(aes(ymin = mean-SE, ymax = mean+SE)) + xlab('Date') + ylab('Water Salinity') + theme(axis.text.x = element_text(size = 7, angle = 45), axis.ticks = element_blank()) + scale_x_discrete(limits = c('01/2017', '02/2017', '03/2017', '04/2017', '05/2017', '06/2017', '07/2017', '08/2017', '09/2017', '10/2017', '11/2017', '12/2017', '01/2018', '02/2018', '03/2018', '04/2018', '05/2018', '06/2018', '07/2018', '08/2018', '09/2018', '10/2018', '11/2018', '12/2018', '01/2019', '02/2019', '03/2019', '04/2019', '05/2019', '06/2019', '07/2019', '08/2019', '09/2019', '10/2019', '11/2019', '12/2019', '01/2020', '02/2020', '03/2020', '04/2020', '05/2020', '06/2020', '07/2020', '08/2020', '09/2020', '10/2020', '11/2020', '12/2020', '01/2021', '02/2021', '03/2021', '04/2021', '05/2021', '06/2021'))
```

#Neritinia usnea threshold: <18
#Littoraria irrorata threshold: >2
#looking at days below lit threshold
```{r}
less <- sal %>% subset(Sal < 2)

litdays <- less %>% 
  group_by(`Date`) %>% 
  summarise(mean = mean(Sal),
            SE = std.error(Sal))

litmonth <- less %>% 
  group_by(`Month/Year`) %>% 
  summarise(mean = mean(Sal),
            SE = std.error(Sal))

litdays2 <- read_xlsx('litdays.xlsx')
sum(with(litdays2,Year == "2017"))
#33 days in 2017
sum(with(litdays2,Year == "2018"))
#7 days in 2018
sum(with(litdays2,Year == "2019"))
#51 days in 2019
sum(with(litdays2,Year == "2020"))
#31 days in 2020
```

#looking at above nerite threshold
```{r}
more <- sal %>% subset(Sal > 18)

nerdays <- more %>% 
  group_by(`Date`) %>% 
  summarise(mean = mean(Sal),
            SE = std.error(Sal))

nerdays2 <- read_xlsx('nerdays.xlsx')
sum(with(nerdays2,Year == "2017"))
#45 days in 2017
sum(with(nerdays2,Year == "2018"))
#43 days in 2018
sum(with(nerdays2,Year == "2019"))
#9 days in 2019
sum(with(nerdays2,Year == "2020"))
#34
```

